version: '3.8'

services:
  ssl_generator:
    build:
      context: ./ssl_generator
    volumes:
      - ssl_certs:/ssl
    entrypoint: ["/bin/sh", "-c", "/ssl/generate_ssl.sh"]
    restart: "no"

  app:
    build:
      context: .
      dockerfile: crm-app/Dockerfile
    container_name: crm_app
    volumes:
      - ./crm-app:/var/www/html
    depends_on:
      - mysql
    networks:
      - crm_network

  nginx:
    image: nginx:latest
    container_name: crm_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./crm-app:/var/www/html
      - ssl_certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ssl_generator
      - app
    networks:
      - crm_network

  mysql:
    image: mysql:8.0.39
    container_name: crm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: crm_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crm_network

networks:
  crm_network:

volumes:
  mysql_data:
  ssl_certs:
